name: Daily Project to MD

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: |
          npm install
          cd examples
          npm install
      - name: Export project to markdown
        working-directory: examples
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx ts-node project-to-md.ts examples/itesm