name: Sync MD to Project

on:
  push:
    paths:
      - examples/md/**/*.md
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: |
          npm install
          cd examples
          npm install
      - name: Sync markdown to project
        working-directory: examples
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ github.token }}
        run: npx ts-node md-to-project.ts